# Dockerfile.dockerignore for Pulumi RAGFlow image
# Build context is the repo root; only include what we need

# Exclude everything by default
*

# Include pulumi_ragflow/ source files
!pulumi_ragflow/go.mod
!pulumi_ragflow/go.sum
!pulumi_ragflow/*.go
!pulumi_ragflow/Pulumi.yaml
!pulumi_ragflow/Pulumi.ali_k8s.yaml

# Include docker/ files referenced by Go code
!docker/rabbitmq-conf/definitions.json
!docker/rabbitmq-conf/definitions.conf
!docker/entrypoint.sh
!docker/entrypoint-parser.sh
