[supervisord]
nodaemon=true
logfile=/dev/stdout
logfile_maxbytes=0
pidfile=/tmp/supervisord.pid

[unix_http_server]
file=/tmp/supervisor.sock

[supervisorctl]
serverurl=unix:///tmp/supervisor.sock

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[program:redis_exporter]
command=/usr/local/bin/redis_exporter
    --redis.addr=localhost:6379
    --redis.password=infini_rag_flow
    --exclude-latency-histogram-metrics
autostart=true
autorestart=true
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0

[program:mysqld_exporter]
command=/usr/local/bin/mysqld_exporter --config.my-cnf=/etc/exporters/mysqld_exporter.cnf
autostart=true
autorestart=true
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0

[program:elasticsearch_exporter]
command=/usr/local/bin/elasticsearch_exporter --es.uri=http://elastic:infini_rag_flow@localhost:9200 --es.all
autostart=true
autorestart=true
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0