ragflow:
  host: 0.0.0.0
  http_port: 9380
mysql:
  name: 'rag_flow'
  user: 'root'
  password: 'infini_rag_flow'
  host: 'mysql'
  port: 5455
  max_connections: 100
  stale_timeout: 30
minio_0:
  user: 'rag_flow'
  password: 'infini_rag_flow'
  host: 'minio:9000'
es:
  hosts: 'http://es01:1200'
  username: 'elastic'
  password: 'infini_rag_flow'
infinity:
  uri: 'infinity:23817'
  db_name: 'default_db'
redis:
  db: 1
  password: 'infini_rag_flow'
  host: 'redis:6379'
local_embd:
  bge-large-en-v1.5: http://10.142.0.6:4566/predict
  bge-large-zh-v1.5: http://10.142.0.6:4567/predict
  bce-embedding-base_v1: http://10.142.0.6:4568/predict
  bge-m3: http://10.142.0.6:4569/predict
billing:
  stripe_api_key: 'sk_test_51RLgXMPtsKvwvC5fPPYV143r560uZJMUGcgj58nY6tkrisR6h6QN1EUabEeDTHrs4lQofg87KqF90APIs0PpzIN0002ydK7iJI'
  stripe_api_version: '2026-02-25.clover'
  stripe_endpoint_secret: 'whsec_10c6b02840850557fda082a0b74293685b26498bf03eb5cdffd1e6db0d077ad8'
  session_success_url: 'http://127.0.0.1:9222/success.html'
  session_cancel_url: 'http://127.0.0.1:9222/cancel.html'
  # webhook_url: 'https://demo.ragflow.io/v1/billing/webhook'
  webhook_url: 'http://127.0.0.1:9380/v1/billing/webhook'
  customer_portal_return_url: 'http://127.0.0.1:9380'
  plans_cache_key: 'saas:billing:plans:latest'
  usage_based_plans_cache_key: 'saas:billing:usage_based:latest'
  plans_cache_ttl_seconds: 86400
  local_price:
    - product_name: "deepdoc"
      amount: 1
      currency: "usd"
  price_point:
    - product_name: "deepdoc"
      price_type: "usage_based"
      billing_frequency: "one_time"
      unit: "page"
      unit_quantity: 1
      consuming_point_amount: 1  # points charged per page
  points_recharge:
    price_id: "price_1T77p7PtsKvwvC5f7w3uFo6g"
    points_per_unit: 100 # 1 quantity = 1 USD = 100 points (1 cent = 1 point)
  billing_plans:
    - name: "storage"
      quota_apps: 0
      quota_members: 0
      quota_kb_storage: 0
      task_priority: "low"
      price_ids: "price_1Syn0kPtsKvwvC5fd6HYXvCt"
      price_lookup_key: "ragflow_subscription_storage"
      product_type: "usage_based"
      usage_stat_type: "before"
      plan_priority: -1
    - name: "deepdoc"
      quota_apps: 0
      quota_members: 0
      quota_kb_storage: 0
      task_priority: "low"
      price_ids: "price_1RRTpfPtsKvwvC5fVsZly0mE"
      price_lookup_key: "ragflow_usage_based_deepdoc"
      product_type: "usage_based"
      usage_stat_type: "before"
      plan_priority: -1
    - name: "Trial"
      quota_apps: 5
      quota_members: 1
      quota_kb_storage: 100MB
      api_request_limit_per_minute: 500
      api_request_limit_per_month: 5000
      task_priority: "low"
      price_ids: "price_1RWUhlPtsKvwvC5fJHfaYeRs"
      product_type: "subscription"
      usage_stat_type: ""
      plan_priority: 0
    - name: "Starter"
      quota_apps: 100
      quota_members: 10
      quota_kb_storage: 10G
      api_request_limit_per_minute: 2147483647
      api_request_limit_per_month: 2147483647
      task_priority: "high"
      price_ids: "price_1Si7S7PtsKvwvC5f3IjPpPcN"
      price_lookup_key: "lk_ragflow_plan_level_1_20251225"
      product_type: "subscription"
      usage_stat_type: ""
      plan_priority: 1
    - name: "Pro"
      quota_apps: 999999999
      quota_members: 50
      quota_kb_storage: 100G
      api_request_limit_per_minute: 2147483647
      api_request_limit_per_month: 2147483647
      task_priority: "high"
      price_ids: "price_1Si7SyPtsKvwvC5fxloqaKPP"
      price_lookup_key: "lk_ragflow_level2_monthly_20251225"
      product_type: "subscription"
      usage_stat_type: ""
      plan_priority: 2
    - name: "Enterprise"
      quota_apps: 999999999
      quota_members: 50
      quota_kb_storage: 100G
      api_request_limit_per_minute: 2147483647
      api_request_limit_per_month: 2147483647
      task_priority: "high"
      price_ids: "price_1SNQPMPtsKvwvC5fJtR16E6w"
      price_lookup_key: "lk_ragflow_enterprise_monthly"
      product_type: "subscription"
      usage_stat_type: ""
      plan_priority: 3
rabbitmq:
  user: "kevin"
  password: 'kevin'
  host: '192.168.200.143'
  port: 1672
  api_port: 1673
  exchange: "test1"
task_executor:
  message_queue_type: 'rabbitmq'
user_default_llm:
  factory: 'BAAI'
  api_key: ''
  base_url: ''
  default_models:
    embedding_model: 'bge-m3'

# postgres:
#   name: 'rag_flow'
#   user: 'rag_flow'
#   password: 'infini_rag_flow'
#   host: 'postgres'
#   port: 5432
#   max_connections: 100
#   stale_timeout: 30
# s3:
#   access_key: 'access_key'
#   secret_key: 'secret_key'
#   region: 'region'
# azure:
#   auth_type: 'sas'
#   container_url: 'container_url'
#   sas_token: 'sas_token'
# azure:
#   auth_type: 'spn'
#   account_url: 'account_url'
#   client_id: 'client_id'
#   secret: 'secret'
#   tenant_id: 'tenant_id'
#   container_name: 'container_name'
#   factory: 'BAAI'
#   api_key: 'backup'
#   base_url: 'backup_base_url'
#   default_models:
#     chat_model:
#       name: 'qwen2.5-7b-instruct'
#       factory: 'xxxx'
#       api_key: 'xxxx'
#       base_url: 'https://api.xx.com'
#     embedding_model:
#       name: 'bge-m3'
#     rerank_model: 'bge-reranker-v2'
#     asr_model:
#       model: 'whisper-large-v3' # alias of name
#     image2text_model: ''
# oauth:
#   github:
#     client_id: xxxxxxxxxxxxxxxxxxxxxxxxx
#     secret_key: xxxxxxxxxxxxxxxxxxxxxxxxxxxx
#     url: https://github.com/login/oauth/access_token
#   feishu:
#     app_id: cli_xxxxxxxxxxxxxxxxxxx
#     app_secret: xxxxxxxxxxxxxxxxxxxxxxxxxxxx
#     app_access_token_url: https://open.feishu.cn/open-apis/auth/v3/app_access_token/internal
#     user_access_token_url: https://open.feishu.cn/open-apis/authen/v1/oidc/access_token
#     grant_type: 'authorization_code'
#   ldap:
#     url: ldaps://ad01.mycompany.com:636
#     dn: CN=svc_ldap_app, OU=Service Accounts, DC=mycompany, DC=com
#     password: xxxxxxxxxxxxxxxxxxxxxxxxxxxx
#     search_filter: (|(userPrincipalName={username})(mail={username}))
#     attribute_list: cn,mail,uid,givenName,sn,jpegPhoto,sAMAccountName,userPrincipalName
#     login_channel: AD # LDAP
#    ##################
#    # example
#    ##################
#    search_filter: (|(cn={username})(mail={username}))
#    attribute_list: cn,mail # comma seperated
#   google:
#     type: google
#     client_id: 936108576595-fie6xxxxxxxxxxxxxxxxxxxxxxx.apps.googleusercontent.com
#     client_secret: GOCSPX-H6pNxxxxxxxxxxxxxxxxxHL6ZpW8PSL5FU3aL7s
#     redirect_uri: http://<domain>/v1/user/oauth/callback/google
#     display_name: Google
#     icon: google
#
# authentication:
#   client:
#     switch: false
#     http_app_key:
#     http_secret_key:
#   site:
#     switch: false
# permission:
#   switch: false
#   component: false
#   dataset: false
# smtp:
#   mail_server: ""
#   mail_port: 465
#   mail_use_ssl: true
#   mail_use_tls: false
#   mail_username: ""
#   mail_password: ""
#   mail_default_sender:
#     - "RAGFlow" # display name
#     - "" # sender email address
#   mail_frontend_url: "https://your-frontend.example.com"
